// Generated by GitHub Copilot
interface GraphNode {
  node_id: string;
  label: string;
  layer_type: string;
  params: number;
}

interface GraphEdge {
  source: string;
  target: string;
}

interface GraphBoardProps {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

// Generated by GitHub Copilot
/** Render a lightweight layer graph list with explicit edge mapping labels. */
export function GraphBoard({ nodes, edges }: GraphBoardProps): JSX.Element {
  if (nodes.length === 0) {
    return <p className="muted">No graph parsed yet.</p>;
  }

  return (
    <section className="graph-board" aria-label="Model graph board">
      <div className="graph-nodes">
        {nodes.map((node) => (
          <article key={node.node_id} className="graph-node">
            <h4>{node.label}</h4>
            <p className="muted">{node.layer_type}</p>
            <p>Params: {node.params.toLocaleString()}</p>
          </article>
        ))}
      </div>
      <div className="graph-edges">
        <h4>Edges</h4>
        <ul>
          {edges.map((edge) => (
            <li key={`${edge.source}-${edge.target}`}>
              {edge.source} -&gt; {edge.target}
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
}
