// Generated by GitHub Copilot
interface MetricTileProps {
  label: string;
  value: string;
  hint?: string;
}

// Generated by GitHub Copilot
/** Render one analysis metric card for dead/vanishing signal diagnostics. */
export function MetricTile({ label, value, hint }: MetricTileProps): JSX.Element {
  return (
    <article className="metric-tile" aria-label={label}>
      <h3>{label}</h3>
      <p className="metric-value">{value}</p>
      {hint ? <p className="metric-hint">{hint}</p> : null}
    </article>
  );
}
