# Generated by GitHub Copilot
from dataclasses import replace
from pathlib import Path

from fastapi.testclient import TestClient

from app import main as main_module
from app.config import Settings
from app.main import app
from app.store import init_db


# Generated by GitHub Copilot
"""Create isolated app test client with temp sqlite path and test host allowlist."""
def create_test_client(tmp_path: Path, rate_limit_per_minute: int = 120) -> TestClient:
    db_path = tmp_path / "neuralscope_test.sqlite3"
    init_db(str(db_path))

    from app import main as main_module

    main_module.settings = Settings(
        app_env="test",
        host="127.0.0.1",
        port=8030,
        allowed_hosts={"localhost", "127.0.0.1", "testserver"},
        cors_origins=["http://localhost:8110"],
        enable_hsts=False,
        max_payload_bytes=2 * 1024 * 1024,
        rate_limit_per_minute=rate_limit_per_minute,
        db_path=str(db_path),
        api_key="",
    )
    main_module.rate_limiter.clear()

    return TestClient(app)


# Generated by GitHub Copilot
def _assert_error_contract(
    response,
    expected_status: int,
    expected_code: str,
    expected_message: str | None = None,
    expect_details: bool = False,
) -> None:
    """Validate normalized FastAPI error envelopes for contract assertions."""
    assert response.status_code == expected_status
    payload = response.json()
    assert isinstance(payload.get("error"), dict)
    assert payload["error"]["code"] == expected_code
    assert isinstance(payload["error"]["message"], str)
    if expected_message is not None:
        assert payload["error"]["message"] == expected_message
    assert isinstance(payload["error"]["request_id"], str)
    assert payload["error"]["request_id"]
    if expect_details:
        assert "details" in payload["error"]


def test_parse_model_endpoint(tmp_path: Path):
    client = create_test_client(tmp_path)
    response = client.post(
        "/api/v1/models/parse",
        headers={"host": "testserver"},
        json={
            "model_name": "demo-net",
            "framework": "pytorch",
            "layers": [
                {"name": "dense1", "layer_type": "Linear", "input_size": 32, "output_size": 64, "activation": "relu"},
                {"name": "dense2", "layer_type": "Linear", "input_size": 64, "output_size": 10, "activation": "softmax"},
            ],
        },
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["node_count"] == 2
    assert payload["edge_count"] == 1
    assert payload["total_params"] == (32 * 64) + (64 * 10)


def test_analyze_and_list_sessions(tmp_path: Path):
    client = create_test_client(tmp_path)

    analyze_response = client.post(
        "/api/v1/models/analyze",
        headers={"host": "testserver"},
        json={
            "session_name": "gradient-check",
            "activations": [[0.0, 0.2, 0.0], [0.5, 0.0, 0.1]],
            "gradients": [[0.0001, 0.0002, 0.002], [0.01, 0.0, 0.0]],
            "dead_threshold": 0.0001,
            "vanishing_threshold": 0.001,
        },
    )

    assert analyze_response.status_code == 200
    session_id = analyze_response.json()["session_id"]

    list_response = client.get("/api/v1/sessions", headers={"host": "testserver"})
    assert list_response.status_code == 200
    assert len(list_response.json()) == 1

    get_response = client.get(f"/api/v1/sessions/{session_id}", headers={"host": "testserver"})
    assert get_response.status_code == 200
    assert get_response.json()["session_id"] == session_id


def test_probe_alias_endpoints(tmp_path: Path):
    client = create_test_client(tmp_path)

    health_alias = client.get("/healthz", headers={"host": "testserver"})
    assert health_alias.status_code == 200
    assert health_alias.json()["status"] == "ok"

    ready_alias = client.get("/readyz", headers={"host": "testserver"})
    assert ready_alias.status_code == 200
    assert ready_alias.json()["status"] in {"ready", "not_ready"}


def test_host_guard(tmp_path: Path):
    client = create_test_client(tmp_path)
    response = client.get("/health", headers={"host": "blocked.example"})
    _assert_error_contract(
        response,
        expected_status=400,
        expected_code="host_not_allowed",
        expected_message="host_not_allowed",
    )


def test_error_responses_include_security_and_request_headers(tmp_path: Path):
    client = create_test_client(tmp_path)
    response = client.get("/api/v1/sessions/missing-session", headers={"host": "testserver"})

    assert response.status_code == 404
    assert response.headers.get("X-Request-ID")
    assert response.headers.get("X-Content-Type-Options") == "nosniff"
    assert response.headers.get("X-Frame-Options") == "DENY"


def test_phase1_auth_required_contract(tmp_path: Path, monkeypatch):
    """Require API key on protected routes and return normalized unauthorized responses."""
    client = create_test_client(tmp_path)
    monkeypatch.setattr(main_module, "settings", replace(main_module.settings, api_key="phase1-secret"))

    unauthorized = client.get("/api/v1/sessions", headers={"host": "testserver"})
    _assert_error_contract(
        unauthorized,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    invalid_key = client.get("/api/v1/sessions", headers={"host": "testserver", "X-API-Key": "wrong"})
    _assert_error_contract(
        invalid_key,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    authorized = client.get("/api/v1/sessions", headers={"host": "testserver", "X-API-Key": "phase1-secret"})
    assert authorized.status_code == 200


def test_phase1_error_contract_response(tmp_path: Path):
    """Return normalized not-found payloads for unknown session lookups."""
    client = create_test_client(tmp_path)
    response = client.get("/api/v1/sessions/missing-session", headers={"host": "testserver"})
    _assert_error_contract(
        response,
        expected_status=404,
        expected_code="not_found",
        expected_message="session_not_found",
    )


def test_rate_limit_enforcement_contract(tmp_path: Path):
    client = create_test_client(tmp_path, rate_limit_per_minute=1)

    first = client.get("/api/v1/sessions", headers={"host": "testserver"})
    assert first.status_code == 200

    second = client.get("/api/v1/sessions", headers={"host": "testserver"})
    _assert_error_contract(
        second,
        expected_status=429,
        expected_code="rate_limited",
        expected_message="rate_limited",
    )
    assert second.headers.get("Retry-After") == "60"
    assert second.headers.get("X-Request-ID")
