# Generated by GitHub Copilot
from pathlib import Path

from fastapi.testclient import TestClient

from app.config import Settings
from app.main import app
from app.store import init_db


# Generated by GitHub Copilot
"""Create isolated app test client with temp sqlite path and test host allowlist."""
def create_test_client(tmp_path: Path) -> TestClient:
    db_path = tmp_path / "neuralscope_test.sqlite3"
    init_db(str(db_path))

    from app import main as main_module

    main_module.settings = Settings(
        app_env="test",
        host="127.0.0.1",
        port=8030,
        allowed_hosts={"localhost", "127.0.0.1", "testserver"},
        cors_origins=["http://localhost:8110"],
        enable_hsts=False,
        max_payload_bytes=2 * 1024 * 1024,
        db_path=str(db_path),
    )

    return TestClient(app)


def test_parse_model_endpoint(tmp_path: Path):
    client = create_test_client(tmp_path)
    response = client.post(
        "/api/v1/models/parse",
        headers={"host": "testserver"},
        json={
            "model_name": "demo-net",
            "framework": "pytorch",
            "layers": [
                {"name": "dense1", "layer_type": "Linear", "input_size": 32, "output_size": 64, "activation": "relu"},
                {"name": "dense2", "layer_type": "Linear", "input_size": 64, "output_size": 10, "activation": "softmax"},
            ],
        },
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["node_count"] == 2
    assert payload["edge_count"] == 1
    assert payload["total_params"] == (32 * 64) + (64 * 10)


def test_analyze_and_list_sessions(tmp_path: Path):
    client = create_test_client(tmp_path)

    analyze_response = client.post(
        "/api/v1/models/analyze",
        headers={"host": "testserver"},
        json={
            "session_name": "gradient-check",
            "activations": [[0.0, 0.2, 0.0], [0.5, 0.0, 0.1]],
            "gradients": [[0.0001, 0.0002, 0.002], [0.01, 0.0, 0.0]],
            "dead_threshold": 0.0001,
            "vanishing_threshold": 0.001,
        },
    )

    assert analyze_response.status_code == 200
    session_id = analyze_response.json()["session_id"]

    list_response = client.get("/api/v1/sessions", headers={"host": "testserver"})
    assert list_response.status_code == 200
    assert len(list_response.json()) == 1

    get_response = client.get(f"/api/v1/sessions/{session_id}", headers={"host": "testserver"})
    assert get_response.status_code == 200
    assert get_response.json()["session_id"] == session_id


def test_host_guard(tmp_path: Path):
    client = create_test_client(tmp_path)
    response = client.get("/health", headers={"host": "blocked.example"})
    assert response.status_code == 400
    assert response.json()["error"] == "host_not_allowed"
