# Generated by GitHub Copilot
import os
from dataclasses import dataclass


@dataclass(frozen=True)
class Settings:
    app_env: str
    host: str
    port: int
    allowed_hosts: set[str]
    cors_origins: list[str]
    enable_hsts: bool
    max_payload_bytes: int
    db_path: str


# Generated by GitHub Copilot
"""Parse comma-separated values into a trimmed list."""
def parse_csv(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


# Generated by GitHub Copilot
"""Build runtime settings from environment variables."""
def get_settings() -> Settings:
    return Settings(
        app_env=os.getenv("APP_ENV", "development"),
        host=os.getenv("NEURALSCOPE_HOST", "0.0.0.0"),
        port=int(os.getenv("NEURALSCOPE_PORT", "8030")),
        allowed_hosts=set(parse_csv(os.getenv("NEURALSCOPE_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver"))),
        cors_origins=parse_csv(
            os.getenv("NEURALSCOPE_CORS_ORIGINS", "http://localhost:8110,http://127.0.0.1:8110")
        ),
        enable_hsts=os.getenv("NEURALSCOPE_ENABLE_HSTS", "false").lower() == "true",
        max_payload_bytes=int(os.getenv("NEURALSCOPE_MAX_PAYLOAD_BYTES", "4194304")),
        db_path=os.getenv("NEURALSCOPE_DB_PATH", "./backend/data/neuralscope.sqlite3"),
    )
