# Generated by GitHub Copilot
import asyncio

from fastapi import FastAPI, HTTPException, Request, Response, WebSocket, WebSocketDisconnect, status
from fastapi.middleware.cors import CORSMiddleware

from .config import get_settings
from .middleware import apply_security_headers, is_allowed_host
from .models import ModelParseRequest, ModelParseResponse, SessionSummary, SignalAnalysisRequest, SignalAnalysisResponse
from .service import analyze_signals, parse_model_graph
from .store import create_session, db_ready, get_session, init_db, list_sessions

settings = get_settings()
init_db(settings.db_path)

app = FastAPI(title="neuralscope", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def request_guards(request: Request, call_next):
    host_header = request.headers.get("host", "")
    if not is_allowed_host(host_header, settings.allowed_hosts):
        return Response(content='{"error":"host_not_allowed"}', media_type="application/json", status_code=400)

    if request.headers.get("content-length"):
        content_length = int(request.headers["content-length"])
        if content_length > settings.max_payload_bytes:
            return Response(content='{"error":"payload_too_large"}', media_type="application/json", status_code=413)

    response = await call_next(request)
    return apply_security_headers(response, settings.enable_hsts)


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/ready")
def ready(response: Response) -> dict[str, str]:
    if not db_ready(settings.db_path):
        response.status_code = status.HTTP_503_SERVICE_UNAVAILABLE
        return {"status": "not_ready"}
    return {"status": "ready"}


@app.post("/api/v1/models/parse", response_model=ModelParseResponse)
def parse_model(payload: ModelParseRequest) -> dict:
    return parse_model_graph(payload)


@app.post("/api/v1/models/analyze", response_model=SignalAnalysisResponse)
def analyze_model_signals(payload: SignalAnalysisRequest) -> dict:
    try:
        result = analyze_signals(payload)
    except ValueError as error:
        raise HTTPException(status_code=400, detail=str(error)) from error

    return create_session(settings.db_path, result)


@app.get("/api/v1/sessions", response_model=list[SessionSummary])
def fetch_sessions() -> list[dict]:
    return list_sessions(settings.db_path)


@app.get("/api/v1/sessions/{session_id}")
def fetch_session(session_id: str) -> dict:
    session = get_session(settings.db_path, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="session_not_found")
    return session


@app.websocket("/ws/sessions/{session_id}")
async def stream_session(session_id: str, websocket: WebSocket):
    await websocket.accept()
    session = get_session(settings.db_path, session_id)
    if not session:
        await websocket.send_json({"error": "session_not_found"})
        await websocket.close(code=1008)
        return

    try:
        for progress in (20, 50, 80, 100):
            await websocket.send_json(
                {
                    "session_id": session_id,
                    "progress": progress,
                    "status": "streaming" if progress < 100 else "complete",
                }
            )
            await asyncio.sleep(0.2)
    except WebSocketDisconnect:
        return
    finally:
        await websocket.close()
