# Generated by GitHub Copilot
import asyncio
from collections import deque
from threading import Lock
from time import monotonic
from uuid import uuid4

from fastapi import Depends, FastAPI, Header, HTTPException, Request, Response, WebSocket, WebSocketDisconnect, status
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

from .config import get_settings
from .middleware import apply_security_headers, is_allowed_host
from .models import ModelParseRequest, ModelParseResponse, SessionSummary, SignalAnalysisRequest, SignalAnalysisResponse
from .service import analyze_signals, parse_model_graph
from .store import create_session, db_ready, get_session, init_db, list_sessions

settings = get_settings()
init_db(settings.db_path)
AUTH_EXEMPT_PATHS = {
    "/",
    "/health",
    "/ready",
    "/healthz",
    "/readyz",
    "/docs",
    "/openapi.json",
    "/redoc",
}


# Generated by GitHub Copilot
class InMemoryRateLimiter:
    """Simple in-memory fixed-window limiter keyed by client identifier."""

    def __init__(self, window_seconds: float = 60.0) -> None:
        self.window_seconds = window_seconds
        self._events: dict[str, deque[float]] = {}
        self._lock = Lock()

    def allow(self, key: str, limit: int) -> bool:
        """Return True when request is within configured per-minute limit."""
        now = monotonic()
        cutoff = now - self.window_seconds

        with self._lock:
            timeline = [timestamp for timestamp in self._events.get(key, []) if timestamp >= cutoff]
            if len(timeline) >= limit:
                self._events[key] = deque(timeline)
                return False

            timeline.append(now)
            self._events[key] = deque(timeline)
            return True

    def clear(self) -> None:
        """Clear limiter state for deterministic tests."""
        with self._lock:
            self._events.clear()


rate_limiter = InMemoryRateLimiter(window_seconds=60.0)


# Generated by GitHub Copilot
def _request_id_from_request(request: Request) -> str:
    """Read request correlation id from request state or fallback headers."""
    request_id = getattr(request.state, "request_id", None)
    if isinstance(request_id, str) and request_id:
        return request_id
    return request.headers.get("X-Request-ID", "unknown")


# Generated by GitHub Copilot
def _build_error_payload(
    request: Request,
    code: str,
    message: str,
    details: object | None = None,
) -> dict[str, object]:
    """Build standardized error payloads for all API failures."""
    payload: dict[str, object] = {
        "error": {
            "code": code,
            "message": message,
            "request_id": _request_id_from_request(request),
        }
    }
    if details is not None:
        payload["error"]["details"] = details
    return payload


# Generated by GitHub Copilot
def _guard_error_response(
    request: Request,
    request_id: str,
    status_code: int,
    code: str,
    message: str,
    details: object | None = None,
    extra_headers: dict[str, str] | None = None,
) -> JSONResponse:
    """Build early-guard responses with normalized payload and security headers."""
    response = JSONResponse(
        status_code=status_code,
        content=_build_error_payload(request, code=code, message=message, details=details),
    )
    response = apply_security_headers(response, settings.enable_hsts)
    response.headers["X-Request-ID"] = request_id
    if extra_headers:
        for header_name, header_value in extra_headers.items():
            response.headers[header_name] = header_value
    return response


# Generated by GitHub Copilot
def _status_to_error_code(status_code: int) -> str:
    """Map HTTP statuses to stable contract error codes."""
    mapping = {
        400: "bad_request",
        401: "unauthorized",
        403: "forbidden",
        404: "not_found",
        409: "conflict",
        413: "payload_too_large",
        422: "validation_error",
        429: "rate_limited",
    }
    if status_code >= 500:
        return "internal_error"
    return mapping.get(status_code, "request_failed")


# Generated by GitHub Copilot
def _require_api_key(
    request: Request,
    x_api_key: str | None = Header(default=None, alias="X-API-Key"),
) -> None:
    """Enforce optional API key auth for non-probe routes."""
    if request.method == "OPTIONS" or request.url.path in AUTH_EXEMPT_PATHS:
        return
    if not settings.api_key:
        return
    if x_api_key != settings.api_key:
        raise HTTPException(status_code=401, detail="api_key_invalid")

app = FastAPI(title="neuralscope", version="0.1.0", dependencies=[Depends(_require_api_key)])

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def request_guards(request: Request, call_next):
    """Enforce host and payload guards and propagate request correlation ids."""
    request_id = request.headers.get("X-Request-ID", str(uuid4()))
    request.state.request_id = request_id

    host_header = request.headers.get("host", "")
    if not is_allowed_host(host_header, settings.allowed_hosts):
        return _guard_error_response(
            request=request,
            request_id=request_id,
            status_code=400,
            code="host_not_allowed",
            message="host_not_allowed",
        )

    if request.headers.get("content-length"):
        try:
            content_length = int(request.headers["content-length"])
        except ValueError:
            return _guard_error_response(
                request=request,
                request_id=request_id,
                status_code=400,
                code="bad_request",
                message="invalid_content_length",
            )

        if content_length > settings.max_payload_bytes:
            return _guard_error_response(
                request=request,
                request_id=request_id,
                status_code=413,
                code="payload_too_large",
                message="payload_too_large",
            )

    if request.method != "OPTIONS" and request.url.path not in AUTH_EXEMPT_PATHS:
        client_key = request.client.host if request.client and request.client.host else "unknown"
        if not rate_limiter.allow(client_key, settings.rate_limit_per_minute):
            return _guard_error_response(
                request=request,
                request_id=request_id,
                status_code=429,
                code="rate_limited",
                message="rate_limited",
                extra_headers={"Retry-After": "60"},
            )

    response = await call_next(request)
    response = apply_security_headers(response, settings.enable_hsts)
    response.headers["X-Request-ID"] = request_id
    return response


# Generated by GitHub Copilot
@app.exception_handler(StarletteHTTPException)
@app.exception_handler(HTTPException)
async def handle_http_exception(request: Request, exc: HTTPException) -> JSONResponse:
    """Return normalized error payloads for expected HTTP failures."""
    message = str(exc.detail) if exc.detail is not None else "request_failed"
    return JSONResponse(
        status_code=exc.status_code,
        content=_build_error_payload(
            request=request,
            code=_status_to_error_code(exc.status_code),
            message=message,
        ),
    )


# Generated by GitHub Copilot
@app.exception_handler(RequestValidationError)
async def handle_validation_exception(request: Request, exc: RequestValidationError) -> JSONResponse:
    """Return normalized payloads for validation failures."""
    return JSONResponse(
        status_code=422,
        content=_build_error_payload(
            request=request,
            code="validation_error",
            message="request_validation_failed",
            details=exc.errors(),
        ),
    )


# Generated by GitHub Copilot
@app.exception_handler(Exception)
async def handle_unexpected_exception(request: Request, _: Exception) -> JSONResponse:
    """Return normalized payloads for unhandled internal errors."""
    return JSONResponse(
        status_code=500,
        content=_build_error_payload(
            request=request,
            code="internal_error",
            message="internal_server_error",
        ),
    )


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/ready")
def ready(response: Response) -> dict[str, str]:
    if not db_ready(settings.db_path):
        response.status_code = status.HTTP_503_SERVICE_UNAVAILABLE
        return {"status": "not_ready"}
    return {"status": "ready"}


# Generated by GitHub Copilot
@app.get("/healthz", include_in_schema=False)
def healthz() -> dict[str, str]:
    """Compatibility alias for health probes expecting /healthz."""
    return health()


# Generated by GitHub Copilot
@app.get("/readyz", include_in_schema=False)
def readyz(response: Response) -> dict[str, str]:
    """Compatibility alias for readiness probes expecting /readyz."""
    return ready(response)


@app.post("/api/v1/models/parse", response_model=ModelParseResponse)
def parse_model(payload: ModelParseRequest) -> dict:
    return parse_model_graph(payload)


@app.post("/api/v1/models/analyze", response_model=SignalAnalysisResponse)
def analyze_model_signals(payload: SignalAnalysisRequest) -> dict:
    try:
        result = analyze_signals(payload)
    except ValueError as error:
        raise HTTPException(status_code=400, detail=str(error)) from error

    return create_session(settings.db_path, result)


@app.get("/api/v1/sessions", response_model=list[SessionSummary])
def fetch_sessions() -> list[dict]:
    return list_sessions(settings.db_path)


@app.get("/api/v1/sessions/{session_id}")
def fetch_session(session_id: str) -> dict:
    session = get_session(settings.db_path, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="session_not_found")
    return session


@app.websocket("/ws/sessions/{session_id}")
async def stream_session(session_id: str, websocket: WebSocket):
    await websocket.accept()
    session = get_session(settings.db_path, session_id)
    if not session:
        await websocket.send_json({"error": "session_not_found"})
        await websocket.close(code=1008)
        return

    try:
        for progress in (20, 50, 80, 100):
            await websocket.send_json(
                {
                    "session_id": session_id,
                    "progress": progress,
                    "status": "streaming" if progress < 100 else "complete",
                }
            )
            await asyncio.sleep(0.2)
    except WebSocketDisconnect:
        return
    finally:
        await websocket.close()
