# Generated by GitHub Copilot
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class LayerSpec(BaseModel):
    name: str = Field(min_length=1, max_length=80)
    layer_type: str = Field(min_length=1, max_length=80)
    input_size: int = Field(ge=1)
    output_size: int = Field(ge=1)
    activation: str = Field(default="relu", max_length=40)


class ModelParseRequest(BaseModel):
    model_name: str = Field(min_length=1, max_length=120)
    framework: Literal["pytorch", "tensorflow", "onnx", "custom"]
    layers: list[LayerSpec] = Field(min_length=1)


class GraphNode(BaseModel):
    node_id: str
    label: str
    layer_type: str
    params: int


class GraphEdge(BaseModel):
    source: str
    target: str


class ModelParseResponse(BaseModel):
    model_name: str
    framework: str
    total_params: int
    node_count: int
    edge_count: int
    nodes: list[GraphNode]
    edges: list[GraphEdge]


class SignalAnalysisRequest(BaseModel):
    session_name: str = Field(min_length=1, max_length=140)
    activations: list[list[float]] = Field(min_length=1)
    gradients: list[list[float]] = Field(min_length=1)
    dead_threshold: float = Field(default=0.0001, ge=0.0)
    vanishing_threshold: float = Field(default=0.001, ge=0.0)


class SignalAnalysisResponse(BaseModel):
    session_id: str
    session_name: str
    created_at: datetime
    dead_neuron_ratio: float
    vanishing_gradient_ratio: float
    alerts: list[str]


class SessionSummary(BaseModel):
    session_id: str
    session_name: str
    created_at: datetime
    dead_neuron_ratio: float
    vanishing_gradient_ratio: float
