# Generated by GitHub Copilot
from datetime import datetime, timezone
from uuid import uuid4

from .models import ModelParseRequest, SignalAnalysisRequest


# Generated by GitHub Copilot
"""Convert layer list to simple directed graph metadata and parameter estimates."""
def parse_model_graph(payload: ModelParseRequest) -> dict:
    nodes: list[dict] = []
    edges: list[dict] = []
    total_params = 0

    for index, layer in enumerate(payload.layers):
        params = layer.input_size * layer.output_size
        total_params += params

        node_id = f"layer-{index}"
        nodes.append(
            {
                "node_id": node_id,
                "label": f"{layer.name} ({layer.activation})",
                "layer_type": layer.layer_type,
                "params": params,
            }
        )

        if index > 0:
            edges.append({"source": f"layer-{index - 1}", "target": node_id})

    return {
        "model_name": payload.model_name,
        "framework": payload.framework,
        "total_params": total_params,
        "node_count": len(nodes),
        "edge_count": len(edges),
        "nodes": nodes,
        "edges": edges,
    }


# Generated by GitHub Copilot
"""Compute dead-neuron and vanishing-gradient ratios from numeric tensors."""
def analyze_signals(payload: SignalAnalysisRequest) -> dict:
    activation_values = [value for row in payload.activations for value in row]
    gradient_values = [value for row in payload.gradients for value in row]

    if not activation_values:
        raise ValueError("Activation tensor cannot be empty")
    if not gradient_values:
        raise ValueError("Gradient tensor cannot be empty")

    dead_count = sum(1 for value in activation_values if abs(value) <= payload.dead_threshold)
    vanishing_count = sum(1 for value in gradient_values if abs(value) <= payload.vanishing_threshold)

    dead_ratio = dead_count / len(activation_values)
    vanishing_ratio = vanishing_count / len(gradient_values)

    alerts: list[str] = []
    if dead_ratio >= 0.35:
        alerts.append("Dead neuron ratio is elevated")
    if vanishing_ratio >= 0.40:
        alerts.append("Vanishing gradient risk detected")

    session_id = str(uuid4())
    created_at = datetime.now(timezone.utc).isoformat()

    return {
        "session_id": session_id,
        "session_name": payload.session_name,
        "created_at": created_at,
        "dead_neuron_ratio": dead_ratio,
        "vanishing_gradient_ratio": vanishing_ratio,
        "alerts": alerts,
        "payload": payload.model_dump(),
    }
