# Generated by GitHub Copilot
import json
import os
import sqlite3
from contextlib import closing
from typing import Any


CREATE_SESSIONS_TABLE = """
CREATE TABLE IF NOT EXISTS analysis_sessions (
    session_id TEXT PRIMARY KEY,
    session_name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    dead_neuron_ratio REAL NOT NULL,
    vanishing_gradient_ratio REAL NOT NULL,
    alerts_json TEXT NOT NULL,
    payload_json TEXT NOT NULL
)
"""


# Generated by GitHub Copilot
"""Initialize sqlite schema and parent folder for session storage."""
def init_db(db_path: str) -> None:
    parent = os.path.dirname(db_path)
    if parent:
        os.makedirs(parent, exist_ok=True)

    with closing(sqlite3.connect(db_path)) as connection:
        with closing(connection.cursor()) as cursor:
            cursor.execute(CREATE_SESSIONS_TABLE)
        connection.commit()


# Generated by GitHub Copilot
"""Run a minimal DB probe for readiness status."""
def db_ready(db_path: str) -> bool:
    try:
        with closing(sqlite3.connect(db_path)) as connection:
            with closing(connection.cursor()) as cursor:
                cursor.execute("SELECT 1")
                cursor.fetchone()
        return True
    except sqlite3.Error:
        return False


# Generated by GitHub Copilot
"""Insert analysis session row and return persisted session summary."""
def create_session(db_path: str, session: dict[str, Any]) -> dict[str, Any]:
    with closing(sqlite3.connect(db_path)) as connection:
        with closing(connection.cursor()) as cursor:
            cursor.execute(
                """
                INSERT INTO analysis_sessions (
                    session_id, session_name, created_at, dead_neuron_ratio,
                    vanishing_gradient_ratio, alerts_json, payload_json
                )
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    session["session_id"],
                    session["session_name"],
                    session["created_at"],
                    session["dead_neuron_ratio"],
                    session["vanishing_gradient_ratio"],
                    json.dumps(session["alerts"], separators=(",", ":"), ensure_ascii=True),
                    json.dumps(session["payload"], separators=(",", ":"), ensure_ascii=True),
                ),
            )
        connection.commit()

    return session


# Generated by GitHub Copilot
"""List stored analysis sessions with latest first ordering."""
def list_sessions(db_path: str, limit: int = 50) -> list[dict[str, Any]]:
    with closing(sqlite3.connect(db_path)) as connection:
        connection.row_factory = sqlite3.Row
        with closing(connection.cursor()) as cursor:
            cursor.execute(
                """
                SELECT session_id, session_name, created_at, dead_neuron_ratio, vanishing_gradient_ratio
                FROM analysis_sessions
                ORDER BY created_at DESC
                LIMIT ?
                """,
                (limit,),
            )
            rows = cursor.fetchall()

    return [dict(row) for row in rows]


# Generated by GitHub Copilot
"""Fetch a single session including payload and alert details."""
def get_session(db_path: str, session_id: str) -> dict[str, Any] | None:
    with closing(sqlite3.connect(db_path)) as connection:
        connection.row_factory = sqlite3.Row
        with closing(connection.cursor()) as cursor:
            cursor.execute(
                """
                SELECT session_id, session_name, created_at, dead_neuron_ratio,
                       vanishing_gradient_ratio, alerts_json, payload_json
                FROM analysis_sessions
                WHERE session_id = ?
                LIMIT 1
                """,
                (session_id,),
            )
            row = cursor.fetchone()

    if not row:
        return None

    result = dict(row)
    result["alerts"] = json.loads(result.pop("alerts_json"))
    result["payload"] = json.loads(result.pop("payload_json"))
    return result
