// Generated by GitHub Copilot
import { useEffect, useMemo, useState } from "react";

import { GraphBoard } from "./components/GraphBoard";
import { MetricTile } from "./components/MetricTile";
import { analyzeSignals, fetchSessions, parseModel, type AnalysisResult, type ParsedGraph, type SessionSummary } from "./lib/api";

const DEFAULT_MODEL_PAYLOAD = {
  model_name: "fraud-detector-v2",
  framework: "pytorch",
  layers: [
    { name: "dense1", layer_type: "Linear", input_size: 32, output_size: 64, activation: "relu" },
    { name: "dense2", layer_type: "Linear", input_size: 64, output_size: 32, activation: "relu" },
    { name: "dense3", layer_type: "Linear", input_size: 32, output_size: 2, activation: "softmax" },
  ],
};

const DEFAULT_ANALYSIS_PAYLOAD = {
  session_name: "fraud-v2-check",
  activations: [
    [0.0, 0.12, 0.0, 0.56],
    [0.4, 0.0, 0.09, 0.0],
  ],
  gradients: [
    [0.0001, 0.001, 0.02, 0.0],
    [0.003, 0.0004, 0.0, 0.0002],
  ],
  dead_threshold: 0.0001,
  vanishing_threshold: 0.001,
};

// Generated by GitHub Copilot
/** Render neural debugging dashboard for graph parse, signal analysis, and session history. */
export default function App(): JSX.Element {
  const [modelInput, setModelInput] = useState(JSON.stringify(DEFAULT_MODEL_PAYLOAD, null, 2));
  const [analysisInput, setAnalysisInput] = useState(JSON.stringify(DEFAULT_ANALYSIS_PAYLOAD, null, 2));
  const [parsedGraph, setParsedGraph] = useState<ParsedGraph | null>(null);
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
  const [sessions, setSessions] = useState<SessionSummary[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    void refreshSessions();
  }, []);

  // Generated by GitHub Copilot
  /** Refresh persisted analysis sessions from API storage. */
  async function refreshSessions(): Promise<void> {
    try {
      const rows = await fetchSessions();
      setSessions(rows);
    } catch (apiError) {
      setError(apiError instanceof Error ? apiError.message : "Failed to load sessions");
    }
  }

  // Generated by GitHub Copilot
  /** Parse user model JSON payload into graph response state. */
  async function onParseModel(): Promise<void> {
    setError(null);
    try {
      const payload = JSON.parse(modelInput) as unknown;
      const response = await parseModel(payload);
      setParsedGraph(response);
    } catch (apiError) {
      setError(apiError instanceof Error ? apiError.message : "Failed to parse model payload");
    }
  }

  // Generated by GitHub Copilot
  /** Run activation and gradient diagnostics and refresh session history. */
  async function onAnalyzeSignals(): Promise<void> {
    setError(null);
    try {
      const payload = JSON.parse(analysisInput) as unknown;
      const response = await analyzeSignals(payload);
      setAnalysisResult(response);
      await refreshSessions();
    } catch (apiError) {
      setError(apiError instanceof Error ? apiError.message : "Failed to analyze signal payload");
    }
  }

  const tiles = useMemo(() => {
    if (!analysisResult) {
      return [];
    }

    return [
      { label: "Dead Neuron Ratio", value: analysisResult.dead_neuron_ratio.toFixed(3) },
      { label: "Vanishing Gradient Ratio", value: analysisResult.vanishing_gradient_ratio.toFixed(3) },
      { label: "Alerts", value: String(analysisResult.alerts.length), hint: analysisResult.alerts.join(", ") || "No alerts" },
    ];
  }, [analysisResult]);

  return (
    <main className="page">
      <header className="hero" aria-labelledby="title">
        <h1 id="title">neuralscope debugger</h1>
        <p>Inspect model graph structure and diagnose dead neurons or vanishing gradients before deployment.</p>
      </header>

      <section className="panel" aria-labelledby="parse-title">
        <h2 id="parse-title">Parse Model Graph</h2>
        <label>
          Model Payload (JSON)
          <textarea value={modelInput} rows={10} onChange={(event) => setModelInput(event.target.value)} spellCheck={false} />
        </label>
        <button type="button" onClick={() => void onParseModel()}>Parse Graph</button>
        {parsedGraph ? (
          <p className="muted">Total params: {parsedGraph.total_params.toLocaleString()} | Nodes: {parsedGraph.node_count}</p>
        ) : null}
        <GraphBoard nodes={parsedGraph?.nodes || []} edges={parsedGraph?.edges || []} />
      </section>

      <section className="panel" aria-labelledby="analyze-title">
        <h2 id="analyze-title">Analyze Activations and Gradients</h2>
        <label>
          Analysis Payload (JSON)
          <textarea value={analysisInput} rows={10} onChange={(event) => setAnalysisInput(event.target.value)} spellCheck={false} />
        </label>
        <div className="actions">
          <button type="button" onClick={() => void onAnalyzeSignals()}>Run Analysis</button>
          <button type="button" className="secondary" onClick={() => void refreshSessions()}>Refresh Sessions</button>
        </div>
        <div className="tile-grid">
          {tiles.map((tile) => (
            <MetricTile key={tile.label} label={tile.label} value={tile.value} hint={tile.hint} />
          ))}
        </div>
        {analysisResult && analysisResult.alerts.length > 0 ? (
          <ul className="alerts">
            {analysisResult.alerts.map((alert) => (
              <li key={alert}>{alert}</li>
            ))}
          </ul>
        ) : null}
      </section>

      <section className="panel" aria-labelledby="sessions-title">
        <h2 id="sessions-title">Session History</h2>
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Session</th>
                <th>Dead Ratio</th>
                <th>Vanishing Ratio</th>
                <th>Created</th>
              </tr>
            </thead>
            <tbody>
              {sessions.map((session) => (
                <tr key={session.session_id}>
                  <td>{session.session_name}</td>
                  <td>{session.dead_neuron_ratio.toFixed(3)}</td>
                  <td>{session.vanishing_gradient_ratio.toFixed(3)}</td>
                  <td>{new Date(session.created_at).toLocaleString()}</td>
                </tr>
              ))}
              {sessions.length === 0 ? (
                <tr>
                  <td colSpan={4} className="muted">No sessions yet.</td>
                </tr>
              ) : null}
            </tbody>
          </table>
        </div>
      </section>

      {error ? <p className="error" role="alert">{error}</p> : null}
    </main>
  );
}
