// Generated by GitHub Copilot
export interface ParsedGraph {
  model_name: string;
  framework: string;
  total_params: number;
  node_count: number;
  edge_count: number;
  nodes: Array<{ node_id: string; label: string; layer_type: string; params: number }>;
  edges: Array<{ source: string; target: string }>;
}

export interface AnalysisResult {
  session_id: string;
  session_name: string;
  created_at: string;
  dead_neuron_ratio: number;
  vanishing_gradient_ratio: number;
  alerts: string[];
}

export interface SessionSummary {
  session_id: string;
  session_name: string;
  created_at: string;
  dead_neuron_ratio: number;
  vanishing_gradient_ratio: number;
}

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8030";

// Generated by GitHub Copilot
/** Parse model layer payload into graph metadata and complexity summary. */
export async function parseModel(payload: unknown): Promise<ParsedGraph> {
  const response = await fetch(`${API_BASE_URL}/api/v1/models/parse`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const details = await response.json().catch(() => ({ detail: "Failed to parse model" }));
    throw new Error(details.detail || "Failed to parse model");
  }

  return (await response.json()) as ParsedGraph;
}

// Generated by GitHub Copilot
/** Analyze activation and gradient tensors for dead and vanishing signals. */
export async function analyzeSignals(payload: unknown): Promise<AnalysisResult> {
  const response = await fetch(`${API_BASE_URL}/api/v1/models/analyze`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const details = await response.json().catch(() => ({ detail: "Failed to analyze signals" }));
    throw new Error(details.detail || "Failed to analyze signals");
  }

  return (await response.json()) as AnalysisResult;
}

// Generated by GitHub Copilot
/** Fetch saved session summaries for debugging history and comparisons. */
export async function fetchSessions(): Promise<SessionSummary[]> {
  const response = await fetch(`${API_BASE_URL}/api/v1/sessions`);
  if (!response.ok) {
    throw new Error("Failed to fetch sessions");
  }

  return (await response.json()) as SessionSummary[];
}
